export default {
  name: 'occupation',
  title: 'Occupation',
  type: 'document',
  groups: [
    {
      name: 'occupation_head',
      title: 'Occupation Head',
    },
    {
      name: 'visa_options',
      title: 'Visa Options',
    },
    {
      name: 'state/territory',
      title: 'State/Territory',
    },
    {
      name: 'anzsco_section',
      title: 'Anzsco Section',
    },
    {
      name: 'backlog_section',
      title: 'Backlog Section',
    },
  ],
  fields: [
    {
      name: 'occupation',
      title: 'Occupation',
      type: 'reference',
      to: [{ type: 'occupation_head' }],
      group: 'occupation_head',
      validation: (Rule: { required: () => any }) => Rule.required(),
    },
    {
      name: 'skill_level',
      title: 'Skill Level',
      type: 'string',
      validation: (Rule: { required: () => any }) => Rule.required(),

      options: {
        list: ['1', '2', '3', '4', '5'],
        layout: 'radio',
        direction: 'horizontal',
      },
    },
    {
      name: 'assessing_authority',
      title: 'Assessing Authority',
      type: 'string',
      validation: (Rule: { required: () => any }) => Rule.required(),
      options: {
        list: [
          { title: 'AACA', value: 'AACA' },
          { title: 'AASW', value: 'AASW' },
          { title: 'ACECQA', value: 'ACECQA' },
          { title: 'ACS', value: 'ACS' },
          { title: 'ACWA', value: 'ACWA' },
          { title: 'ADC', value: 'ADC' },
          { title: 'AIMS', value: 'AIMS' },
          { title: 'AIQS', value: 'AIQS' },
          { title: 'AITSL', value: 'AITSL' },
          { title: 'ANMAC', value: 'ANMAC' },
          { title: 'ANZSNM', value: 'ANZSNM' },
          { title: 'AOAC', value: 'AOAC' },
          { title: 'AOPA', value: 'AOPA' },
          { title: 'APC', value: 'APC' },
          { title: 'APharmC', value: 'APharmC' },
          { title: 'APS', value: 'APS' },
          { title: 'ASMIRT', value: 'ASMIRT' },
          { title: 'AVBC', value: 'AVBC' },
          { title: 'CASA', value: 'CASA' },
          { title: 'CCEA', value: 'CCEA' },
          { title: 'CMBA', value: 'CMBA' },
          { title: 'CPAA', value: 'CPAA' },
          { title: 'CAANZ', value: 'CAANZ' },
          { title: 'IPA', value: 'IPA' },
          { title: 'DDA', value: 'DDA' },
          { title: 'EA', value: 'EA' },
          { title: 'IML', value: 'IML' },
          { title: 'MedBA', value: 'MedBA' },
          { title: 'NAATI', value: 'NAATI' },
          { title: 'OCANZ', value: 'OCANZ' },
          { title: 'OTC', value: 'OTC' },
          { title: 'PodBA', value: 'PodBA' },
          { title: 'SLAA', value: 'SLAA' },
          { title: 'SPA', value: 'SPA' },
          { title: 'SSSI', value: 'SSSI' },
          { title: 'TRA', value: 'TRA' },
          { title: 'VETASSESS', value: 'VETASSESS' },
          { title: 'ACPSEM', value: 'ACPSEM' },
        ], // <-- predefined values
        layout: 'radio', // <-- defaults to 'dropdown'
        direction: 'horizontal',
      },
    },
    {
      name: 'visa_option_section',
      title: 'Visa Options',
      type: 'array',
      of: [{ type: 'visa_option_obj' }],
      group: 'visa_options',
      validation: (Rule: { required: () => any }) => Rule.required(),
    },
    {
      name: 'territory_section',
      title: 'State/Territory',
      type: 'array',
      of: [{ type: 'territory_obj' }],
      group: 'state/territory',
      validation: (Rule: { required: () => any }) => Rule.required(),
    },
    {
      name: 'anzsco_section',
      title: 'Anzsco Section',
      type: 'anzsco_obj',
      group: 'anzsco_section',
      validation: (Rule: { required: () => any }) => Rule.required(),
    },
    {
      name: 'backlog_section',
      title: 'Backlog Section',
      type: 'backlog_obj',
      group: 'backlog_section',
      validation: (Rule: { required: () => any }) => Rule.required(),
    },
  ],
  preview: {
    select: {
      title: 'title',
    },
  },
};
